export { default as Answers } from "./Answers";
export * from "./App";
export * from "./Community";
export * from "./CoursesInfo";
export * from "./Footer";
export * from "./Image";
export * from "./Infocards";
export * from "./Navbar";
export { default as Paragraph } from "./Paragraph";
export * from "./Titles";
